# Main zsh config file
# Where all config files are located
BASE="$HOME/.dotfiles"
ZSH="$BASE/zsh"

typeset -U config_files
config_files=($ZSH/*.zsh)
for cfile in ${${config_files:#*/completion.zsh}}
do
	source $cfile
done
unset config_files

# Init autocomplete here
autoload -U compinit
compinit
source $ZSH/completion.zsh

# Load local config if exists
# This would contain any passwords or sensitive data
# It goes without saying that this file should be ignored by VCS systems
LOCAL_FILE="$HOME/.localrc"
[[ -f $LOCAL_FILE ]] && . $LOCAL_FILE


# JINA_CLI_BEGIN

## autocomplete
if [[ ! -o interactive ]]; then
    return
fi

compctl -K _jina jina

_jina() {
  local words completions
  read -cA words

  if [ "${#words}" -eq 2 ]; then
    completions="$(jina commands)"
  else
    completions="$(jina completions ${words[2,-2]})"
  fi

  reply=(${(ps:
:)completions})
}

# session-wise fix
ulimit -n 4096
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# JINA_CLI_END







