[icons]
icons = "awesome6"

[theme.overrides]
name = "plain"
separator = "  ⁞ "
separator_bg = "#1d1f21"
idle_fg = "#f3f4f5"
idle_bg = "#1d1f21"
critical_bg = "#ff0000"
critical_fg = "#ffffff"
warning_fg = "#f3f4f5"
warning_bg = "#1d1f21"
good_bg = "#1d1f21"
good_fg = "#20bf6b"
info_bg = "#1d1f21"
info_fg = "#20bf6b"


[[block]]
block = "custom"
command = '''bash /home/breda/.dotfiles/scripts/i3status-rs-healthcheck.sh https://store-api.trulyexperiences.com/health https://admin-api.trulyexperiences.com/health'''
format = "truly $text"
json = true
interval = 20

# Blocks
[[block]]
block = "temperature"
format = "$icon $average"
interval = 5
chip = "*-isa-*"

[[block]]
block = "memory"
format = "mem $mem_used_percents.eng(w:2)"
interval = 5

[[block]]
block = "cpu"
format = "cpu $utilization"
interval = 2

[[block]]
block = "amd_gpu"
format = "gpu $utilization"
interval = 2

[[block]]
block = "net"
format = "{wifi $signal_strength $ssid $frequency|eth}"
missing_format = "no net"
interval = 15

[[block]]
block = "time"
interval = 5
timezone = "Africa/Algiers"
[block.format]
full = "$timestamp.datetime(f:'%a %d %B %H:%M', l:en_GB) "
short = "$timestamp.datetime(f:%R) "


